// Auto-generated by deploy.js — do not edit manually
// Generated: 2026-02-22T15:33:03.662Z

const CONTRACTS = {
  USDT:    "0x0477BeD86FeA5c4c0ae4bC3AAdbEe42D76273e22",
  AUSD:    "0x122b9C153c7AB589465505f01E8bdA66552f768D",
  ORACLE:  "0x631100C996aBFea0d81233D4DF446a816E124C97",
  VAULT:   "0x2D633Eb5371b00e1459a26FAd237d255bdbb7560",
  PERPS:   "0xda2057b0d68503E38C4FFbd74DF163073b1eD80b",
};

const CHAINLINK = {
  AVAX_USD_FEED: "0x5498BB86BC934c8D34FDA08E81D444153d0D06aD",
  docs: "https://data.chain.link/avalanche/mainnet/crypto-usd/avax-usd",
};

const NETWORK = {
  chainId: 43113,
  name: "fuji",
  rpc: "https://api.avax-test.network/ext/bc/C/rpc",
  explorer: "https://testnet.snowtrace.io",
};

const COMMODITIES = [
  { id: 0, name: "Cocoa",    symbol: "COCOA",   unit: "MT", flag: "🍫" },
  { id: 1, name: "Palm Oil", symbol: "PALMOIL", unit: "MT", flag: "🌴" },
  { id: 2, name: "Maize",    symbol: "MAIZE",   unit: "MT", flag: "🌽" },
  { id: 3, name: "Soybean",  symbol: "SOYBEAN", unit: "MT", flag: "🫘" },
];
