// Auto-generated by deploy.js — do not edit manually
// Generated: 2026-02-25T21:04:56.594Z

const CONTRACTS = {
  USDT:    "0x30e9a40e757254FA41889c1fA1588D76E3CD3AD4",
  AUSD:    "0x89B9c9d05A7F566107D31b6606eD54f0d7E4A84D",
  ORACLE:  "0x9BacC4b3FE6ad2664bC331C7354Fc3d4cdf4348b",
  VAULT:   "0x40f199cb423b44EA5321e89Fc44988464E286420",
  PERPS:   "0xA0283BcC42CEFb7Cb93Cd0EA5E7A0A80fEc5c636",
};

const CHAINLINK = {
  AVAX_USD_FEED: "0x5498BB86BC934c8D34FDA08E81D444153d0D06aD",
  docs: "https://data.chain.link/avalanche/mainnet/crypto-usd/avax-usd",
};

const NETWORK = {
  chainId: 43113,
  name: "fuji",
  rpc: "https://api.avax-test.network/ext/bc/C/rpc",
  explorer: "https://testnet.snowtrace.io",
};

const COMMODITIES = [
  { id: 0, name: "Cocoa",    symbol: "COCOA",   unit: "MT", flag: "🍫" },
  { id: 1, name: "Palm Oil", symbol: "PALMOIL", unit: "MT", flag: "🌴" },
  { id: 2, name: "Maize",    symbol: "MAIZE",   unit: "MT", flag: "🌽" },
  { id: 3, name: "Soybean",  symbol: "SOYBEAN", unit: "MT", flag: "🫘" },
];
