// Auto-generated by deploy.js — do not edit manually
// Generated: 2026-02-22T12:51:39.211Z

const CONTRACTS = {
  USDT:    "0x2700E6f99dBe91283aC17bB0D03a5E34Da484451",
  ORACLE:  "0x3970Fa8330D04C05288f7f9364c881769DE9B2BE",
  VAULT:   "0xb797efC9664346fc6Af4A1F1627f693142e4370f",
  PERPS:   "0x25dC09e167ef0F222BAaef43bD98FFFf06Fa9538",
};

const NETWORK = {
  chainId: 43113,
  name: "fuji",
  rpc: "https://api.avax-test.network/ext/bc/C/rpc",
  explorer: "https://testnet.snowtrace.io",
};

const COMMODITIES = [
  { id: 0, name: "Cocoa",    symbol: "COCOA",   unit: "MT",  flag: "🍫" },
  { id: 1, name: "Palm Oil", symbol: "PALMOIL", unit: "MT",  flag: "🌴" },
  { id: 2, name: "Maize",    symbol: "MAIZE",   unit: "MT",  flag: "🌽" },
  { id: 3, name: "Soybean",  symbol: "SOYBEAN", unit: "MT",  flag: "🫘" },
];
